[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
pushers = "1.4.2"
tokio = {version = "1.47.1", features = ["full"]}
clap = { version = "4.5.48", features = ["derive"] }
serde_json = "1.0"
