[package]
name = "sockudo"
version = "2.0.1"
edition = "2024"
repository = "https://github.com/RustNSparks/sockudo"
license-file = "LICENSE"
description = "A simple, fast, and secure WebSocket server for real-time applications."

[dependencies]
axum = { version = "^0.8.4", features = ["ws"] }
tokio = { version = "^1", features = ["full"] }
tower-http = { version = "^0.6.4", features = ["cors"] }
fastwebsockets = { version = "0.10.0", features = [
    "upgrade",
    "with_axum",
    "unstable-split",
    "hyper-util",
    "hyper",
] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "^2.0.9"
dashmap = "^6.1.0"
futures = "0.3.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
regex = "1.11.1"
hmac = "0.13.0-pre.4"
sha2 = "0.11.0-pre.4"
hex = "0.4.3"
rand = "0.9.0"
hyper-util = "^0.1.10"
hyper = "^1.5.0"
chrono = "^0.4.41"
sysinfo = "^0.36.1"
async-trait = "0.1.83"
redis = { version = "^0.32.4", features = ["tokio-comp", "json", "cluster", "cluster-async", "tls-rustls"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "mysql", "postgres"] }
aws-config = { version = "^1.6", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.71.1"
urlencoding = "2.1.3"
futures-util = "0.3.31"
tower-layer = "0.3.3"
tower-service = "0.3.3"
prometheus = "0.14.0"
moka = { version = "0.12.10", features = ["future"] }
reqwest = { version = "0.12.15", features = ["json"] }
aws-sdk-sqs = "1.65.0"
async-nats = "0.42.0"
aws-sdk-lambda = "1.76.0"
url = { version = "2.3.1", features = ["serde"] }
axum-server = { version = "^0.7.2", features = ["tls-rustls"] }
axum-extra = { version = "^0.10.1", features = ["typed-header"] }
http = "1.3.1"
ahash = "0.8.12"
clap = { version = "4.5.38", features = ["derive"] }
md5 = "0.8.0"
serde_urlencoded = "0.7"
http-body-util = "0.1.3"
mockall = "0.13.1"

[dependencies.uuid]
version = "1.11.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[profile.release]
codegen-units = 1
lto = true

[package.metadata.binstall]
pkg-url = "https://github.com/RustNSparks/sockudo/releases/download/v{version}/sockudo-v{version}-{target}.{archive_ext}"
pkg-fmt = "tgz"
supported-targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc"
]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "https://github.com/RustNSparks/sockudo/releases/download/v{version}/sockudo-v{version}-{target}.zip"
pkg-fmt = "zip"
